name: example_using_material_symbols_icons 
description: Example package using pub.dev/packages/material_symbols_icons package.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.5
  material_symbols_icons:
    path: ../
  device_preview_plus: ^2.0.4    # (moved from `device_preview` to updated `device_preview_plus`) required only for virtual device screen testing
  splittable_flexible_row: ^1.0.0
  universal_html: ^2.2.3
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
