name: material_symbols_icons
description: Full flutter support for latest Google Material Symbols Icons.
version: 4.2659.0
homepage: https://github.com/timmaffett/material_symbols_icons
screenshots:
  - description: 'example flutter material symbols icon browser'
    path: media/example.png
  - description: 'google material symbols icon browser'
    path: media/google_icon_fonts.png

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  args: ^2.3.1
  path: ^1.8.2

flutter:
  fonts:
    - family: MaterialSymbolsOutlined
      fonts:
       - asset: lib/fonts/MaterialSymbolsOutlined[FILL,GRAD,opsz,wght].ttf
       
    - family: MaterialSymbolsRounded
      fonts:
       - asset: lib/fonts/MaterialSymbolsRounded[FILL,GRAD,opsz,wght].ttf
       
    - family: MaterialSymbolsSharp
      fonts:
       - asset: lib/fonts/MaterialSymbolsSharp[FILL,GRAD,opsz,wght].ttf
    