name: material_symbols_icons
description: Full flutter support for latest Google Material Symbols Icons.
version: 4.39.0
homepage: http://github.com/timmaffett/material_symbols_icons

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  args: ^2.4.0
  path: ^1.8.2

flutter:
  fonts:
    - family: MaterialSymbolsOutlined
      fonts:
       - asset: lib/fonts/MaterialSymbolsOutlined[FILL,GRAD,opsz,wght].ttf
       
    - family: MaterialSymbolsRounded
      fonts:
       - asset: lib/fonts/MaterialSymbolsRounded[FILL,GRAD,opsz,wght].ttf
       
    - family: MaterialSymbolsSharp
      fonts:
       - asset: lib/fonts/MaterialSymbolsSharp[FILL,GRAD,opsz,wght].ttf
    