name: material_symbols_icons
description: Full flutter support for latest Google Material Symbols Icons.
maintainer: Tim Maffett
version: 4.2815.0
homepage: https://github.com/timmaffett/material_symbols_icons
repository: https://github.com/timmaffett/material_symbols_icons
issue_tracker: https://github.com/timmaffett/material_symbols_icons/issues
screenshots:
  - description: 'example flutter material symbols icon browser'
    path: media/example.png
  - description: 'google material symbols icon browser'
    path: media/google_icon_fonts.png

topics:
  - icon
  - icons
  - material
  - material-symbols
  - material-symbols-icons

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  args: ^2.6.0
  path: ^1.9.0
  chalkdart: ^3.0.4
  glob: ^2.1.2

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: MaterialSymbolsOutlined
      fonts:
       - asset: lib/fonts/MaterialSymbolsOutlined.ttf
       
    - family: MaterialSymbolsRounded
      fonts:
       - asset: lib/fonts/MaterialSymbolsRounded.ttf
       
    - family: MaterialSymbolsSharp
      fonts:
       - asset: lib/fonts/MaterialSymbolsSharp.ttf
    
executables:
  install_material_symbols_icons_fonts:

